import './globals.css';

export const metadata = {
  title: 'ZERO',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <head> 
          <link rel="icon" href="/images/favicon.png" sizes="16x16" />
        </head>
        <body>
          <main>
            {children}
          </main>
        </body>
      </html>
  );
}

